### ISSUE TITLE
pls share "Peer-graded Assignment: Peer-graded Assignment: Project Initiation and Set-Up" / Project Management Foundations, Initiation, and Planning

### ISSUE THREAD

**Issue by johnfelipe** [dennislamcv1/IBMITProjMgr#1]

**Comment by dennislamcv1** [comment]
Hi John, I am auditing this whole course, please do not do it as IBM has not released all courses. You can refer the MCQ answers as a guide. I am just looking at the materials roughly to see what is it about.

**Comment by dennislamcv1** [comment]
Hello I just added Scrum Master Honors Project Assignment today

**Comment by dennislamcv1** [comment]
I have added the rest of the assignment work, some I can't do
